#!/bin/sh
# This file is in the public domain
#
# Used to first revoke a key and then restart the exchange
# to ensure it notices the revocation.
#
# Takes 2 arguments:
# $1: the configuration file name
# $2: the denomination key hash (DKH) of the denomination to revoke

set -eu

if [ "$#" -ne 2 ];
then
  echo "illegal number of parameters"
  exit 1
fi

taler-exchange-keyup -c $1 -r $2

EXCHANGE_PID=`ps x | grep taler-exchange-httpd | awk '{print $1}'`
kill -SIGUSR1 $EXCHANGE_PID

exit 0
