.Dd May 5, 2017
.Dt TALER-EXCHANGE-WIREWATCH 1
.Os
.Sh NAME
.Nm taler-exchange-wirewatch
.Nd watch for incoming wire transfers
.Sh SYNOPSIS
.Nm
.Op Fl t Ar PLUGINNAME | Fl -type= Ns Ar PLUGINNAME
.Op Fl h | -help
.Op Fl T | -test
.Op Fl r | -reset
.Op Fl v | -version
.Sh DESCRIPTION
.Nm
is a command line tool to import wire transactions into the
Taler exchange database.
.Pp
Its options are as follows:
.Bl -tag -width indent
.It Fl t Ar PLUGINNAME | Fl -type= Ns Ar PLUGINNAME
Use the specified wire plugin and its configuration to talk to the bank.
.It Fl h | -help
Print short help on options.
.It Fl T | -test
Run in test mode and exit when idle.
.It Fl r | -reset
Ignore our own database and start with transactions
from the beginning of time.
.It Fl v | -version
Print version information.
.El
.Sh SEE ALSO
.Xr taler-exchange-aggregator 1 ,
.Xr taler-exchange-httpd 1 ,
.Xr taler.conf 5 .
.Sh BUGS
Report bugs by using
.Lk https://gnunet.org/bugs/
or by sending electronic mail to
.Aq Mt taler@gnu.org .
