.Dd December 14, 2017
.Dt TALER-BANK-TRANSFER 1
.Os
.Sh NAME
.Nm taler-bank-transfer
.Nd
trigger a transfer at the bank
.Sh SYNOPSIS
.Nm
.Op Fl a Ar VALUE | Fl \-amount= Ns Ar VALUE
.Op Fl b Ar URL | Fl \-bank= Ns Ar URL
.Op Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
.Op Fl h | \-help
.Op Fl D Ar ACCOUNT | Fl \-debit= Ns Ar ACCOUNT
.Op Fl C Ar ACCOUNT | Fl \-credit= Ns Ar ACCOUNT
.Op Fl s Ar STRING | Fl \-subject= Ns Ar STRING
.Op Fl u Ar USERNAME | Fl \-user= Ns Ar USERNAME
.Op Fl p Ar PASSPHRASE | Fl \-pass= Ns Ar PASSPHRASE
.Op Fl v | \-version
.Sh DESCRIPTION
.Nm
is a command line tool to trigger bank transfers.
.Bl -tag -width Ds
.It Fl a Ar VALUE | Fl \-amount= Ns Ar VALUE
Amount to transfer.
Given in the Taler\-typical format of CURRENCY:VALUE.FRACTION
.It Fl b Ar URL | Fl \-bank= Ns Ar URL
URL at which the bank is operation.
.It Fl c Ar FILENAME | Fl \-config= Ns Ar FILENAME
Use the given configuration file.
.It Fl h | \-help
Print short help on options.
.It Fl D Ar ACCOUNT | Fl \-debit= Ns Ar ACCOUNT
The money should be debited from ACCOUNT.
Specifies the number of the account.
.It Fl C Ar ACCOUNT | Fl \-credit= Ns Ar ACCOUNT
The money should be credited to ACCOUNT.
Specifies the number of the account.
.It Fl s Ar STRING | Fl \-subject= Ns Ar STRING
Use STRING for the wire transfer subject.
.It Fl u Ar USERNAME | Fl \-user= Ns Ar USERNAME
Specifies the username for authentication.
.It Fl p Ar PASSPHRASE | Fl \-pass= Ns Ar PASSPHRASE
Specifies the pass phrase for authentication.
.It Fl v | \-version
Print version information.
.El
.Sh SEE ALSO
.Xr taler-bank-manage 1 ,
.Xr taler.conf 5
.Sh BUGS
Report bugs by using
.Lk https://gnunet.org/bugs/
or by sending electronic mail to
.Aq Mt taler@gnu.org
