.TH TALER.CONF 5 "Apr 11, 2016" "GNU Taler"

.SH NAME
taler.conf \- Taler configuration file.

.SH SYNOPSIS
.B taler.conf

.SH DESCRIPTION

The basic structure of the configuration file is the following.  The file is split into sections.  Every section begins with "[SECTIONNAME]" and contains a number of options of the form "OPTION=VALUE".  Empty lines and lines beginning with a "#" are treated as comments.  Files containing default values for many of the options described below are installed under $TALER\_PREFIX/share/taler/config.d/. The configuration file given with \-c to Taler binaries overrides these defaults.

.SH EXCHANGE OPTIONS

The following options are from the "[exchange]" section and used by most exchange tools:

.IP CURRENCY
    Name of the currency, i.e. "EUR" for Euro.
.IP DB
    Plugin to use for the database, i.e. "postgres"
.IP PORT
    Port on which the HTTP server listens, i.e. 8080.
.IP MASTER_PUBLIC_KEY
    Crockford Base32-encoded master public key, public version of the exchange\'s long\-time offline signing key.


.SH WIRE transfer details

To enable the "test" wire transfer method, you must set "ENABLE = YES" in "[exchange\-wire\-test]".
Then, the following options must be in section "[exchange\-wire\-incoming\-test]" and "[exchange\-wire\-outgoing\-test]":

.IP BANK_URI
    URL of the Taler bank.

.IP BANK_ACCOUNT_NUMBER
    Number of the bank account of the exchange.

To enable the "sepa" wire transfer method, you must set "ENABLE = YES" in "[exchange\-wire\-sepa]".
Then, the following options must be in section "[exchange\-wire\-incoming\-sepa]" and "[exchange\-wire\-outgoing\-sepa]":

.IP SEPA_RESPONSE_FILE
    Filename with the JSON body for the /wire response, signed using the exchange\'s long-term offline master key.  Use taler\-exchange\-sepa to create the SEPA_RESPONSE_FILE.


.SH Postgres database options

The following options must be in section "[exchangedb\-postgres]":

.IP DB_CONN_STR
    How to access the database, i.e. "postgres:///taler" to use the "taler" database. Testcases use "talercheck".

.SH COIN OPTIONS

The following options must be in sections starting with "[coin_]" and are used by taler\-exchange\-keyup to create denomination keys:

.IP VALUE
    Value of the coin, i.e. "EUR:1.50" for 1 Euro and 50 Cents (per coin).
.IP DURATION_OVERLAP
    How much should validity periods for these coins overlap?
.IP DURATION_WITHDRAW
    How long should the same key be used for clients to withdraw coins of this value?
.IP DURATION_SPEND
    How long do clients have to spend these coins?
.IP FEE_WITHDRAW
    What fee is charged for withdrawl?
.IP FEE_DEPOSIT
    What fee is charged for depositing?
.IP FEE_REFRESH
    What fee is charged for refreshing?
.IP FEE_REFUND
    What fee is charged for refunds? When a coin is refunded, the deposit fee is returned. Instead, the refund fee is charged to the customer.
.IP RSA_KEYSIZE
    What is the RSA keysize modulos (in bits)?

.SH KEY OPTIONS

The following options are from the "[exchange_keys]" section and used by most taler\-exchange\-keyup to create keys:

.IP SIGNKEY_DURATION
    For how long is a signing key valid?
.IP LEGAL_DURATION
    For how long are signatures with signing keys legally valid?
.IP LOOKAHEAD_SIGN
    How long do we generate denomination and signing keys ahead of time?
.IP LOOKAHEAD_PROVIDE
    How long into the future do we provide signing and denomination keys to clients?


.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <taler@gnu.org>

.SH "SEE ALSO"
\fBtaler\-exchange\-httpd\fP(1), \fBtaler\-exchange\-keyup\fP(1), \fBtaler\-exchange\-reservemod\fP(1), \fBtaler\-exchange\-dbinit\fP(1), \fBtaler\-exchange\-sepa(1)
