.TH TALER\-MINT\-RESERVEMOD 1 "Apr 22, 2015" "GNU Taler"

.SH NAME
taler\-mint\-reservemod \- Modify reserve balance in the Taler mint database.

.SH SYNOPSIS
.B taler\-mint\-reservemod
.RI [ options ]
.br

.SH DESCRIPTION
\fBtaler\-mint\-reservemod\fP is a command line tool to modify reserves in the Taler mint database.  Basically, it can be used to import deposits, either for testing or as part of the import from the list of incoming transactions. 

.SH OPTIONS
.B
.IP "\-a DENOM,  \-\-add=DENOM"
Amount to add to the reserve.
.B
.IP "\-d DIRNAME,  \-\-mint-dir=DIRNAME"
Use the configuration and other resources for the mint to operate from DIRNAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-R KEY,  \-\-reserve=KEY"
Public EdDSA key of the reserve to modify.
.B
.IP "\-v, \-\-version"
Print version information.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <taler@gnu.org>

.SH "SEE ALSO"
\fBtaler\-mint\-httpd\fP(1), \fBtaler\-mint\-keyup\fP(1), \fBtaler\-mint\-dbinit\fP(1), \fBtaler.conf\fP(5)
