.Dd Mar 30, 2016
.Dt TALER-EXCHANGE-AGGREGATOR 1
.Os
.Sh NAME
.Nm taler-exchange-aggregator
.Nd
Aggregate and execute exchange transactions
.Sh SYNOPSIS
.Nm
.Op Fl d Ar DIRNAME | Fl \-exchange-dir= Ns Ar DIRNAME
.Op Fl h | \-help
.Op Fl t | \-test
.Op Fl v | \-version
.Sh DESCRIPTION
.Nm
is a command line tool to run pending transactions from the Taler exchange.
.Bl -tag -width Ds
.It Fl d Ar DIRNAME | Fl \-exchange-dir= Ns Ar DIRNAME
Use the configuration and other resources for the exchange to operate from
.Ar DIRNAME .
.It Fl h | \-help
Print short help on options.
.It Fl t | \-test
Run in test mode and exit when idle.
.It Fl v | \-version
Print version information.
.El
.Sh SEE ALSO
.Xr taler-exchange-dbinit 1 ,
.Xr taler-exchange-keyup 1 ,
.Xr taler-exchange-httpd 1 ,
.Xr taler.conf 5 .
.Sh BUGS
Report bugs by using
.Lk https://gnunet.org/bugs/
or by sending electronic mail to
.Aq Mt taler@gnu.org .
